### PR TITLE
Restrictor changes for

### PR DESCRIPTION
**Pull request by ostcar**
Move moderator_notes to list_of_speakers

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

**Comment by ostcar** [comment]
@Elblinator what is the status of this?

**Comment by Elblinator** [comment]
It's not forgotten! We trying to tidy up the client right now

**Comment by ostcar** [comment]
@Elblinator everything is rebased, so you can test it

**Comment by luisa-beerboom** [comment]
Needs to be rebased again, because we want to merge soon

**Comment by ostcar** [comment]
Would it be possible to merge the meta PR? Then it would be easier here

**Comment by luisa-beerboom** [comment]
Meta is merged

**Comment by luisa-beerboom** [comment]
Feel free to merge immediately once the conflicts are resolved, then we can merge the client.

**Comment by Elblinator** [comment]
Meta is merged

**Pull request merged**
