### PR TITLE
Ristretto

### PR DESCRIPTION
**Pull request by ostcar**
@FinnStutzenstein I can not find the reason for the "does not exist in cache" error and I don't want to look anymore, because I want to change the cache anyway.

This Pull request introduces a test backend that sounds very good: https://dgraph.io/blog/post/introducing-ristretto-high-perf-go-cache/

There are more things that should be done. For example there is a config how big the cache can get. This config has to be set via a environment variable. I will do this later.

Could you test this PR and check, that it works? The error "does not exist in the cache" can not happen again, because this error message was removed :)

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
I still get errors:
```
Error: calculate key projection/3/content: calculating slide: fetching meeting/1/list_of_speakers_id: meeting/1/list_of_speakers_id does not exist.
```
followed by 
```
Internal Error: get first time restricted data: get values for keys `[projector/2/scroll projector/2/header_font_color projector/2/background_color projector/2/color projector/2/chyron_background_color projector/2/history_projection_ids projector/2/header_h1_color projector/2/width projector/2/used_as_reference_projector_meeting_id projector/2/show_title projector/2/chyron_font_color projector/2/scale projector/2/header_background_color projector/2/name projector/2/aspect_ratio_denominator projector/2/current_projection_ids projector/2/id projector/2/show_header_footer projector/2/aspect_ratio_numerator projector/2/show_logo projector/2/show_clock projection/6/content_object_id projection/6/type projection/6/weight projection/6/content projection/6/id projection/6/options projection/6/stable meeting/1/create_timestamp meeting/1/is_present_in_meeting_ids meeting/1/default_time meeting/1/item_number meeting/1/internal meeting/1/last_name meeting/1/meeting_id meeting/1/state meeting/1/comment_$ meeting/1/modified_final_version meeting/1/poll_ids meeting/1/email meeting/1/voted_ids meeting/1/min_votes_amount meeting/1/pollmethod meeting/1/structure_level_$ meeting/1/max_votes_amount meeting/1/countdown_time meeting/1/phase meeting/1/id meeting/1/description meeting/1/title meeting/1/has_inherited_access_groups meeting/1/global_yes meeting/1/default_password meeting/1/username meeting/1/is_active meeting/1/comment_ids meeting/1/option_ids meeting/1/is_internal meeting/1/votescast meeting/1/vote_weight_$ meeting/1/default_poll_description meeting/1/candidate_ids meeting/1/reason meeting/1/open_posts meeting/1/last_email_send meeting/1/default_number meeting/1/default_vote_weight meeting/1/gender meeting/1/message meeting/1/comment meeting/1/level meeting/1/parent_id meeting/1/global_abstain meeting/1/is_physical_person meeting/1/personal_note_ids meeting/1/agenda_item_id meeting/1/weight meeting/1/onehundred_percent_base meeting/1/number_poll_candidates meeting/1/entitled_group_ids meeting/1/state_extension meeting/1/block_id meeting/1/filesize meeting/1/recommendation_id meeting/1/content_object_id meeting/1/duration meeting/1/tag_ids meeting/1/running meeting/1/number meeting/1/child_ids meeting/1/text meeting/1/is_directory meeting/1/votesinvalid meeting/1/votesvalid meeting/1/about_me meeting/1/lead_motion_id meeting/1/mimetype meeting/1/amendment_paragraph_$ meeting/1/global_option_id meeting/1/closed meeting/1/global_no meeting/1/number_$ meeting/1/majority_method meeting/1/default_structure_level meeting/1/first_name meeting/1/type meeting/1/category_id meeting/1/recommendation_extension meeting/1/speaker_ids meeting/1/sequential_number meeting/1/is_hidden]` from datastore: getOrSet for keys `[projector/2/scroll projector/2/header_font_color projector/2/background_color projector/2/color projector/2/chyron_background_color projector/2/history_projection_ids projector/2/header_h1_color projector/2/width projector/2/used_as_reference_projector_meeting_id projector/2/show_title projector/2/chyron_font_color projector/2/scale projector/2/header_background_color projector/2/name projector/2/aspect_ratio_denominator projector/2/current_projection_ids projector/2/id projector/2/show_header_footer projector/2/aspect_ratio_numerator projector/2/show_logo projector/2/show_clock projection/6/content_object_id projection/6/type projection/6/weight projection/6/content projection/6/id projection/6/options projection/6/stable meeting/1/create_timestamp meeting/1/is_present_in_meeting_ids meeting/1/default_time meeting/1/item_number meeting/1/internal meeting/1/last_name meeting/1/meeting_id meeting/1/state meeting/1/comment_$ meeting/1/modified_final_version meeting/1/poll_ids meeting/1/email meeting/1/voted_ids meeting/1/min_votes_amount meeting/1/pollmethod meeting/1/structure_level_$ meeting/1/max_votes_amount meeting/1/countdown_time meeting/1/phase meeting/1/id meeting/1/description meeting/1/title meeting/1/has_inherited_access_groups meeting/1/global_yes meeting/1/default_password meeting/1/username meeting/1/is_active meeting/1/comment_ids meeting/1/option_ids meeting/1/is_internal meeting/1/votescast meeting/1/vote_weight_$ meeting/1/default_poll_description meeting/1/candidate_ids meeting/1/reason meeting/1/open_posts meeting/1/last_email_send meeting/1/default_number meeting/1/default_vote_weight meeting/1/gender meeting/1/message meeting/1/comment meeting/1/level meeting/1/parent_id meeting/1/global_abstain meeting/1/is_physical_person meeting/1/personal_note_ids meeting/1/agenda_item_id meeting/1/weight meeting/1/onehundred_percent_base meeting/1/number_poll_candidates meeting/1/entitled_group_ids meeting/1/state_extension meeting/1/block_id meeting/1/filesize meeting/1/recommendation_id meeting/1/content_object_id meeting/1/duration meeting/1/tag_ids meeting/1/running meeting/1/number meeting/1/child_ids meeting/1/text meeting/1/is_directory meeting/1/votesinvalid meeting/1/votesvalid meeting/1/about_me meeting/1/lead_motion_id meeting/1/mimetype meeting/1/amendment_paragraph_$ meeting/1/global_option_id meeting/1/closed meeting/1/global_no meeting/1/number_$ meeting/1/majority_method meeting/1/default_structure_level meeting/1/first_name meeting/1/type meeting/1/category_id meeting/1/recommendation_extension meeting/1/speaker_ids meeting/1/sequential_number meeting/1/is_hidden]`: fetching missing values: calculating key projection/6/content: calculating slide: fetching meeting/1/list_of_speakers_id: meeting/1/list_of_speakers_id does not exist.
```
Which is essentially the same error

- Sidenote: Projection errors must be provided through `projection/content`
- The fqfield does not exists since the field name is `list_of_speakers_ids`

I think it is more of an issue with the CLOS slide than the cache. The thing is that even if I project something else the error is still present, so I have to restart the autoupdate service. It would be nice, if the error can also be fixed.

**Comment by ostcar** [comment]
I would say it is a different error. The last error was inside the cache. This time, the relevant part of the error is: `calculating slide: fetching meeting/1/list_of_speakers_id: meeting/1/list_of_speakers_id does not exist.` So the error happens, when the calculated field is created. So your new error is the one of issue #212

**Comment by ostcar** [comment]
@FinnStutzenstein I fixed #212. Could you test this again?

**Comment by FinnStutzenstein** [comment]
Works!

**Review by FinnStutzenstein — APPROVED** [review]
I did not check the code, but from tests in the integrated setup it seems to work.

**Comment by ostcar** [comment]
There are race conditions. If I don't fix them, there could be old data in the cache that never gets updated. I have to think of a way how to solve this.

**Comment by ostcar** [comment]
Maybe I do this later. This version did not work

**Pull request closed without merging**
