### PR TITLE
Restricter: New restriction user/B

### LINKED ISSUE #818: Add new user permissions
see https://github.com/OpenSlides/openslides-backend/issues/2122:

The new restriction mode B for users should be the following (adapted from restriction mode A):
```
Y==X
Y has the OML can_manage_users or higher.
There exists a committee where Y has the CML can_manage and X is in committee/user_ids.
X is in a group of a meeting where Y has user.can_see_personal_data.
```

### PR DESCRIPTION
**Pull request by ostcar**
Fixes #818

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Comment by jsangmeister** [comment]
@ostcar please don't merge PRs which are part of a bigger feature, see https://github.com/OpenSlides/OpenSlides/wiki/Working-with-the-meta-repository#workflow-for-changes-to-the-modelsyml. They should be merged all together to prevent inconsistencies

**Comment by ostcar** [comment]
How can I know this?

**Comment by jsangmeister** [comment]
In the issue, there was a linked backend issue as well as a meta issue in the main repository.

**Comment by jsangmeister** [comment]
Also, the PR should only be merged if the meta PR gets merged right afterwards/together, since now the tests in the meta update PR are failing: https://github.com/OpenSlides/openslides-autoupdate-service/pull/862

**Pull request merged**
