### PR TITLE
Change change of restrict chat_group

### PR DESCRIPTION
**Pull request by ostcar**
https://github.com/OpenSlides/OpenSlides/wiki/chat_group-restrictions/_compare/6ac4a9c9aec0b9644df5e0a4154ac3015dcff2d8...02bcfc5e4ba11fa2b1d1207ef36b6f8ca71f525a

See #370

### CODE REVIEW

**Comment by ostcar** [comment]
@GabrielInTheWorld This is the change in [chat_group](https://github.com/OpenSlides/OpenSlides/wiki/chat_group-restrictions/_compare/6ac4a9c9aec0b9644df5e0a4154ac3015dcff2d8...02bcfc5e4ba11fa2b1d1207ef36b6f8ca71f525a) can you tell me if this fixes #370 or if `chat_message` also needs a change.

**Comment by GabrielInTheWorld** [comment]
@ostcar A user could still not see any `chat_group`, if the `chat_group` has no `read_group_ids` or `write_group_ids`. This is even as `superadmin` the case.

**Review by GabrielInTheWorld — CHANGES_REQUESTED** [review]
@ostcar A user could still not see any `chat_group`, if the `chat_group` has no `read_group_ids` or `write_group_ids`. This is even as `superadmin` the case. Also, the username of another user is still missing.

**Comment by ostcar** [comment]
There seems to be another bug. The superuser is not restricted by the restrictor but get all the data. If there is a bug even with the superuser, then this is not related with this PR. This is probably related with #373.

To fix your issue, I first have to be able to reproduce it. Therefore I have to wait until your client PR is merged or at least ready enough, that I can test it together with the autoupdate-service.

**Comment by GabrielInTheWorld** [comment]
> 
> To fix your issue, I first have to be able to reproduce it. Therefore I have to wait until your client PR is merged or at least ready enough, that I can test it together with the autoupdate-service.

I have a [PR](https://github.com/OpenSlides/openslides-client/pull/676).

> 
> Are there any log messages from the autoupdate service?

Until now, no.

**Comment by ostcar** [comment]
@GabrielInTheWorld I can not reproduce you error. I checked our your PR and this PR and could successfully chat between two different users. I was logged in with the superadmin in firefox and a user that was only in the default group of meeting 1. Both where able to chat in the "General" room.

Maybe you should make sure to have a clean database and all brower caches where deleted.

**Comment by ostcar** [comment]
> > @GabrielInTheWorld I can not reproduce you error. I checked our your PR and this PR and could successfully chat between two different users. I was logged in with the superadmin in firefox and a user that was only in the default group of meeting 1. Both where able to chat in the "General" room.
> > Maybe you should make sure to have a clean database and all brower caches where deleted.
> 
> @ostcar: Which groups are set as `read_groups` and `write_groups`?

I did not configure anything. I just used the default (user-) group and the default chat-groups. I don't know which `read_group` and `write_groups` are configured in the example data.

Does it work for you with the example data?

What steps do I have to do to reproduce your error with our both braches?

**Comment by GabrielInTheWorld** [comment]
> > > @GabrielInTheWorld I can not reproduce you error. I checked our your PR and this PR and could successfully chat between two different users. I was logged in with the superadmin in firefox and a user that was only in the default group of meeting 1. Both where able to chat in the "General" room.
> > > Maybe you should make sure to have a clean database and all brower caches where deleted.
> > 
> > 
> > @ostcar: Which groups are set as `read_groups` and `write_groups`?
> 
> I did not configure anything. I just used the default (user-) group and the default chat-groups. I don't know which `read_group` and `write_groups` are configured in the example data.
> 
> Does it work for you with the example data?
> 
> What steps do I have to do to reproduce your error with our both braches?

I will assign this to @emanuelschuetze. If he can confirm that it works as expected using your branch, then he will approve the PR and merge it.

**Comment by GabrielInTheWorld** [comment]
@ostcar: As discussed with @emanuelschuetze, the users names are not seen...

**Comment by ostcar** [comment]
> @ostcar: As discussed with @emanuelschuetze, the users names are not seen...

Please tell me step by step what I have to do to reproduce this.

**Comment by ostcar** [comment]
I talked with @emanuelschuetze and we found three bugs.

1. The bug with chat_groups, that have no read- or write-group is in the client. You request all (normal) groups of a meeting and from this group all relations over write_group_ids and read_group_ids. So all chat_groups, that have no connected groups are not requested from the client.

The solution is to request the chat_groups via `meeting/chat_group_ids`. Then you get all chat_groups, even groups without a write- or read_group_id.

2. There was a bug in the restrictor code. I fixed it in the last commit. In special situations (like this one) the super-admin did not get all data, but the normal restrictor was used. This was the reason, that the values where restricted even for the superadmin.

3. The third bug is in the models.yml. The field [user/chat_message_$_ids](https://github.com/OpenSlides/openslides-backend/blob/418d5ae743b9e030b8f13c4ba5d4191e51ddeb7c/global/meta/models.yml#L363-L369) is in the restriction_mode B. Fields of the restriction mode B can only be seen by the [user him self](https://github.com/OpenSlides/OpenSlides/wiki/user-restrictions#group-restrictions). So another user can not see the field `user/chat_message_$_ids`. Since the field [chat_message/user_id](https://github.com/OpenSlides/openslides-backend/blob/418d5ae743b9e030b8f13c4ba5d4191e51ddeb7c/global/meta/models.yml#L3266-L3270) is a relation field, it can only been seen, if the request user can also see the related field ([also explained here](https://github.com/OpenSlides/openslides-autoupdate-service/issues/342#issuecomment-963230235)).

To fix this, the models.yml has to be changed and the field `user/chat_message_$_ids` has to be viable to all users, that are allowed to see chat messages. This is not a problem. Since this field is a list-relation, all entries get automatically removed, when the user can not see the  corresponding field`chat_message/user_id`.

**Comment by GabrielInTheWorld** [comment]
> I talked with @emanuelschuetze and we found they bugs.
> 
> 1. The bug with chat_groups, that have no read- or write-group is in the client. You request all (normal) groups of a meeting and from this group all relations over write_group_ids and read_group_ids. So all chat_groups, that have no connected groups are not requested from the client.
> 
> The solution is to request the chat_groups via `meeting/chat_group_ids`. Then you get all chat_groups, even groups without a write- or read_group_id.
> 

Yes, I know. Therefore, I wrote, that only the `user_id` for a `chat_message` is missing.

> 2. There was a bug in the restrictor code. I fixed it in the last commit. In special situations (like this one) the super-admin did not get all data, but the normal restrictor was used. This was the reason, that the values where restricted even for the superadmin.

Ok, great.

> 3. The third bug is in the models.yml. The field [user/chat_message_$_ids](https://github.com/OpenSlides/openslides-backend/blob/418d5ae743b9e030b8f13c4ba5d4191e51ddeb7c/global/meta/models.yml#L363-L369) is in the restriction_mode B. Fields of the restriction mode B can only be seen by the [user him self](https://github.com/OpenSlides/OpenSlides/wiki/user-restrictions#group-restrictions). So another user can not see the field `user/chat_message_$_ids`. Since the field [chat_message/user_id](https://github.com/OpenSlides/openslides-backend/blob/418d5ae743b9e030b8f13c4ba5d4191e51ddeb7c/global/meta/models.yml#L3266-L3270) is a relation field, it can only been seen, if the request user can also see the related field ([also explained here](https://github.com/OpenSlides/openslides-autoupdate-service/issues/342#issuecomment-963230235)).
> 
> To fix this, the models.yml has to be changed and the field `user/chat_message_$_ids` has to be viable to all users, that are allowed to see chat messages. This is not a problem. Since this field is a list-relation, all entries get automatically removed, when the user can not see the corresponding field`chat_message/user_id`.

Alright, then, we will do this.

**Review by GabrielInTheWorld — APPROVED** [review]
I think, we can merge this PR. As far as I see, everything works well, except the usernames of other users. However, we have to fix this at another place.

**Pull request merged**
