### PR TITLE
Export debug keys

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by ostcar** [comment]
As soon as this is merged, the icc and vote service have to import the new version.

**Review by r-peschke — APPROVED** [review]

**Comment by GabrielInTheWorld** [comment]
Looks good!

**Review by GabrielInTheWorld — APPROVED** [review]

**Comment by GabrielInTheWorld** [comment]
Please merge and import the new version in the icc- and vote-service and then ping me, that I merge it in the auth-service.

**Comment by ostcar** [comment]
@GabrielInTheWorld https://github.com/OpenSlides/openslides-icc-service/pull/10

The vote service does not need an update since it is currently not used.

Maybe we should move the go-auth-lib into the auth-repo? It is only this directory: https://github.com/OpenSlides/openslides-autoupdate-service/tree/master/pkg/auth

I don't think the auth lib has to be in the autoupdate-repo

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld [OpenSlides/openslides-icc-service#10](https://github.com/OpenSlides/openslides-icc-service/pull/10)
> 

Nice!

> The vote service does not need an update since it is currently not used.
> 
> Maybe we should move the go-auth-lib into the auth-repo? It is only this directory: https://github.com/OpenSlides/openslides-autoupdate-service/tree/master/pkg/auth
> 
> I don't think the auth lib has to be in the autoupdate-repo

Yes, I think so, too!

Maybe the AU-service and the ICC-service (and later the vote-service, too) could also request the auth-debug-keys from the auth-service. Then we have one central place to manage those keys. It is one request more we have to do, but this is anyway for the development-environment.
What do you think?

**Pull request merged**
