### PR TITLE
Change permission to see reference projector

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by bastianjoel** [comment]
Projections also need to be allowed.

**Comment by bastianjoel** [comment]
`meeting_mediafiles.go` also needs to be adjusted. 

Rest seems to work fine.

**Comment by ostcar** [comment]
@bastianjoel @rrenkert can I merge this?

**Review by bastianjoel — CHANGES_REQUESTED** [review]
No, mediafile projections will not work with this. `meeting_mediafiles.go` still just checks for `ProjectorCanSee` but now also needs to implement the autopilot check.

**Comment by ostcar** [comment]
> No, mediafile projections will not work with this. `meeting_mediafiles.go` still just checks for `ProjectorCanSee` but now also needs to implement the autopilot check.

How should this be changed? Maybe:

```
The user can see a projection linked in `meeting_mediafile/projection_ids`.
```

As a reminder, a user can see a projection, if he has projector.can_manage or can see the projector linked in projection/current_projector_id.

**Comment by ostcar** [comment]
@bastianjoel I changed it. Can you take another look?

**Review by bastianjoel — APPROVED** [review]
LGTM and works :)

You can merge now.

**Pull request merged**
